version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: juriscraper
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: sh docker/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata:
