# Generated by Django 5.2.4 on 2025-07-21 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('cod_uf', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('cod_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('cod_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('cod_servico', models.AutoField(primary_key=True, serialize=False)),
                ('civel', models.BooleanField(default=False)),
                ('criminal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('website_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('cod_lote', models.AutoField(primary_key=True, serialize=False)),
                ('cod_lote_prazo', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.IntegerField()),
                ('prioridade', models.IntegerField()),
                ('cod_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='core.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('cod_pesquisa', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('cpf', models.CharField(max_length=14)),
                ('data_entrada', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('nome_corrigido', models.CharField(blank=True, max_length=255, null=True)),
                ('rg', models.CharField(max_length=20)),
                ('rg_corrigido', models.CharField(blank=True, max_length=20, null=True)),
                ('nascimento', models.DateField()),
                ('mae', models.CharField(max_length=255)),
                ('mae_corrigido', models.CharField(blank=True, max_length=255, null=True)),
                ('anexo', models.TextField(blank=True, null=True)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesquisas', to='core.cliente')),
                ('cod_uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesquisas_uf', to='core.estado')),
                ('cod_uf_nascimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nascimento_uf', to='core.estado')),
                ('cod_uf_rg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rg_uf', to='core.estado')),
                ('cod_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesquisas', to='core.servico')),
            ],
        ),
        migrations.CreateModel(
            name='LotePesquisa',
            fields=[
                ('cod_lote_pesquisa', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cod_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lote_pesquisas', to='core.fornecedor')),
                ('cod_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesquisas_atribuídas', to='core.funcionario')),
                ('cod_funcionario_conclusao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesquisas_concluidas', to='core.funcionario')),
                ('cod_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lote_pesquisas', to='core.lote')),
                ('cod_uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lote_pesquisas', to='core.estado')),
                ('cod_pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.pesquisa')),
            ],
        ),
        migrations.CreateModel(
            name='PesquisaSPV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_spv', models.IntegerField()),
                ('cod_spv_computador', models.IntegerField()),
                ('cod_spv_tipo', models.IntegerField()),
                ('filtro', models.IntegerField()),
                ('resultado', models.IntegerField()),
                ('cod_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesquisas_spv', to='core.funcionario')),
                ('cod_pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spv', to='core.pesquisa')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesquisas_spv', to='core.website')),
            ],
        ),
    ]
